# application.yaml
spring:
  application:
    name: sistema-login
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
logging:
  level:
    root: INFO